name: Test Python Package
on:
  pull_request:
    branches:
      - master
jobs:
  test:
    runs-on: ubuntu-18.04
    name: Run Tests/Linters
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install
        run: |
          pip3 install poetry
          poetry install
      - name: Test
        run: poetry run pytest
